### ISSUE TITLE
QUESTION: Does still working?

### ISSUE THREAD

**Issue by samuel-lujan** [docusign/blog-post-php-laravel-jwt#1]
I'm trying to connect with docusign from my laravel application, and I'm getting success.

**Comment by ivan-dinkov** [comment]
@samuel-lujan AFAIK everything should work. Without any details is hard to say. Would you be able to open a [support case](https://support.docusign.com/s/contactSupport?language=en_US) and ask the case to be transferred to Ivan Dinkov?

**Comment by samuel-lujan** [comment]
For sure.  I'm doing this right now!
